// packages/vue/src/Anchor.tsx
import type { DomProps } from '@/utils'

import { useControllableValue } from 'ahooks'
import { clsx } from 'kotl'
import { useMemo } from 'react'

export type AnchorItem = {
  key: string
  title: string
  children?: AnchorItem[]
}

export interface AnchorProps {
  selectedKey?: string
  onChange?: (key: string) => void
  items: AnchorItem[]
}

const AnchorItems = ({ items, selectedKey, onChange }: Required<AnchorProps>) => {
  return items.map(item => (
    <div className="cursor-pointer px-4 py-1.5" key={item.key}>
      <div
        className={clsx([
          'relative mb-1 block overflow-hidden text-ellipsis whitespace-nowrap only:mb-0',
          item.key === selectedKey ? 'text-primary-500 font-medium' : 'text-gray-700',
        ])}
        onClick={() => onChange(item.key)}
      >
        {item.title}
      </div>
      {item.children && item.children.length > 0 && (
        <AnchorItems items={item.children} selectedKey={selectedKey} onChange={onChange} />
      )}
    </div>
  ))
}

export const Anchor = (props: AnchorProps) => {
  const [value, setValue] = useControllableValue<string>(props, {
    valuePropName: 'selectedKey',
  })
  const offset = useMemo(() => findKeyOffset(props.items, value), [props.items, value])
  const onChange = (key: string) => {
    setValue(key)
  }
  return (
    <div>
      <div className="before:content-[' '] relative ps-[2px] text-sm before:absolute before:start-0 before:top-0 before:h-full before:border-s-2 before:border-s-gray-100">
        {offset !== null && (
          <div
            className="bg-primary-500 absolute start-0 top-1 inline-block h-6 w-[2px] transition-transform"
            style={{
              transform: `translateY(${offset}rem)`,
            }}
          />
        )}
        <AnchorItems items={props.items} selectedKey={value} onChange={onChange} />
      </div>
    </div>
  )
}

export type AnchorGroupProps = DomProps<{
  selectedKey?: string
  onChange?: (key: string) => void
  items: {
    key?: string
    title: string
    children: AnchorItem[]
  }[]
}>

export const AnchorGroup = (props: AnchorGroupProps) => {
  const { items, className, style } = props
  const [value, setValue] = useControllableValue<string>(props, {
    valuePropName: 'selectedKey',
  })
  const onChange = (key: string) => {
    setValue(key)
  }
  return (
    <div className={clsx('z-anchor-group', className)} style={style}>
      {items.map(item => (
        <div className="mt-12 lg:mt-8" key={item.key || item.title}>
          <div className="mb-8 text-sm font-semibold text-slate-900 dark:text-slate-200 lg:mb-3">
            {item.title}
          </div>
          <Anchor items={item.children} selectedKey={value} onChange={onChange} />
        </div>
      ))}
    </div>
  )
}

// packages/vue/src/Anchor/index.tsx
import { type PropType, defineComponent } from 'vue'
import { createAnchorStyle } from '@zonda/style'
import { computed } from 'vue'
import { useControllableValue } from '../utils/useControllableValue'

export type IAnchorItem = {
  key: string
  title: string
  href?: string
  isGroup?: boolean
  children?: IAnchorItem[]
}

export type AnchorProps = {
  selectedKey?: string
  items: IAnchorItem[]
}

// 查找当前 key 在 items 中的位置
function findKeyOffset(items: IAnchorItem[], key: string): number | null {
  let index = 0
  let group = 0
  function find(arr: IAnchorItem[]) {
    for (let i = 0; i < arr.length; i++) {
      const { key: childKey, children } = arr[i]
      if (childKey === key) {
        return true
      }
      index++
      if (children && children.length > 0) {
        if (find(children)) {
          return true
        }
        group++
      }
    }
    return false
  }
  console.log('findKeyOffset')
  if (find(items)) {
    return index * 2 + group * 0.25
    // return index * 2
  }
  return null
}

const AnchorItems = defineComponent({
  name: 'ZAnchorItems',
  props: {
    selectedKey: String,
    items: {
      type: Array as PropType<IAnchorItem[]>,
      default: () => [],
    },
  },
  emits: ['change'],
  setup(props, { emit }) {
    const { css, itemStyler } = createAnchorItemStyle()

    const onChange = (k: string) => emit('change', k)

    return () => (
      <>
        {props.items.map(item => (
          <>
            <div class={css} key="{item.key}">
              <div
                class={itemStyler(item.key === props.selectedKey)}
                onClick={() => onChange(item.key)}
              >
                {item.title}
              </div>
              {item.children && item.children.length > 0 && (
                <AnchorItems
                  items={item.children}
                  selectedKey={props.selectedKey}
                  onChange={onChange}
                />
              )}
            </div>
          </>
        ))}
      </>
    )
  },
})

export const Anchor = defineComponent({
  name: 'Anchor',
  props: {
    selectedKey: String,
    items: {
      type: Array as PropType<IAnchorItem[]>,
      default: () => [],
    },
    isGroup: Boolean,
  },
  emits: {
    'update:selectedKey': (val: string) => {},
    change: (val: string) => {},
  },
  setup(props, { emit }) {
    const [state, setState] = useControllableValue<string>(props, {
      valuePropName: 'selectedKey',
    })

    const offset = computed(() => findKeyOffset(props.items, state.value))

    const onChange = (val: string) => {
      setState(val)
      emit('change', val)
    }

    const { css, warper, cursor } = createAnchorStyle()
    return () => (
      <div class={warper}>
        <div class={css}>
          {typeof offset === 'number' && (
            <div class={cursor} style="{ transform: `translateY(${offset}rem)` }" />
          )}
          {props.isGroup ? (
            props.items.map(group => (
              <div class="z-anchor-group mt-12 lg:mt-8">
                <div class="mb-8 text-sm font-semibold text-slate-900 dark:text-slate-200 lg:mb-3">
                  {group.title}
                </div>
                <AnchorItems
                  items={group.children || []}
                  selectedKey={state.value}
                  onChange={onChange}
                />
              </div>
            ))
          ) : (
            <AnchorItems items={props.items} selectedKey={state.value} onChange={onChange} />
          )}
        </div>
      </div>
    )
  },
})
