// packages/vue/src/Button/index.tsx


import { type PropType,defineComponent,type SlotsType } from 'vue'
import { useStyle } from '../utils/style'
import { createButtonStyle, type ColorName } from '@zonda/style'

const Button = defineComponent({
  name:'ZButton',
  props:{
    variant: {
      type: String as PropType<'default' | 'ghost' | 'link' | 'outline' | 'soft' | 'solid'>,
      default: 'default',
    },
    size: {
      type: String as PropType<'sm' | 'md' | 'lg'>,
      default: 'md',
    },
    color: {
      type: String as PropType<ColorName>,
      default: 'primary',
    },
    pill: Boolean,
    square: Boolean,
    block: Boolean,
    loading: Boolean,
    disabled: Boolean,
  }
  emits:[],
  slots: {} as SlotsType<{ default?(_: {}): any; icon?(_: {}): any }>,
  setup(props,{emit,slots}){

const { css, style, icon } = useStyle(() =>
  createButtonStyle({
    variant: props.variant,
    size: props.size,
    color: props.color,
    pill: props.pill,
    square: props.square,
    block: props.block,
    disabled: props.disabled,
  })

)
 return ()=> <button class={css} disabled={props.disabled} style={style} type="button">
  {
    (loading || loading.icon) && <i class={icon}> 
     {
      loading?   <LoadingIcon class="animate-spin" /> : slots.icon()
     }
   
    
  </i>
  }
 {slots.default()}
</button>


  }
})

// packages/react/src/components/Button/index.tsx
import { useMemo } from 'react'

import type { Color } from '@/utils/colors'
import { LoadingIcon } from '../Icon/LoadingIcon'
import { style } from './style'

export interface ButtonProps {
  color?: Color
  variant?: 'solid' | 'soft' | 'outline' | 'ghost' | 'link'
  size?: 'sm' | 'md' | 'lg'
  block?: boolean
  pill?: boolean
  square?: boolean
  circle?: boolean
  loading?: boolean
  disabled?: boolean

  icon?: JSX.Element
  children?: JSX.Element
}

export function Button(props: ButtonProps) {
  const {
    color = 'primary',
    variant = 'default',
    size = 'md',
    block = false,
    pill = false,
    square = false,
    circle = false,
    loading = false,
    disabled = false,

    icon,
    children,
  } = props
  const { css, vars } = useMemo(
    () => style({ variant, size, block, pill, square, circle, loading, disabled, color }),
    [variant, size, block, pill, square, circle, loading, disabled, color]
  )
  return (
    <button className={css} style={vars} type="button" disabled={disabled}>
      {(icon || loading) && (
        <i className="h-[1em] w-[1em] scale-125 [&_+_span]:ml-1.5 [&_svg]:h-full [&_svg]:w-full">
          {loading ? <LoadingIcon className="animate-spin" /> : icon}
        </i>
      )}
      {children && <span className="inline-flex items-center">{children}</span>}
    </button>
  )
}
